### ISSUE TITLE
Publish sourcecode - How to proceed

### ISSUE THREAD

**Issue by andulv** [64bandil/merlin400#2]
The code for the Merlin 400 consists of three separate projects

- drizzle  - the main application for controlling the hardware 
  python  
  Connects to the API running on AWS, and listens to control-messages from that API.
  Controls User Interface (Buttons + LEDS)
  Controls all hardware (valve motors, pump, heating element, sensors,...)

- drizzle_webapp_api - services running on AWS and app that runs in browser  
  app: typescript / html (react)
  endpoints: ???
  
 - drizzle_wifi_setup - application/scripts for configuring the raspberry pi with dual wifi setup.
 python / bash scripts

I am in the process of reviewing the code and help prepare for releasing the source code.

As a bare minimum, credentials and other confidentials must be removed from several files before releasing. 

This issue is meant for discussions and tracking progress for releasing the code.

**Comment by andulv** [comment]
**drizzle_wifi_setup**
I suggest to release this a a seperate project

There is very little here specific to Drizzle/Merlin 400.

This project might be useful for other vendors that ship RPI Zero based products and want to provide the end-user with a way to connect to their local wifi.

I believe this is of less interest for me and other nerds that are mostly interested in supporting and improving our Merlin 400's.

**Comment by andulv** [comment]
**drizzle_webapp_api**
The api endpoints will probably not released. They are specific to Drizzle's AWS setup.
The react app (the user interface running in the browser) is planned to be released.

My suggestion is to move the app over to the main drizzle project (python application), and let the drizzle application serve the react app straight from the Merlin itself.

**Comment by Mtoh2004** [comment]
I’m not sure how much I can help, but I agree with separating out the WiFi. Thanks for getting this started!

**Comment by dkuchay** [comment]
Are STL files available? I have a broken part on my Merlin and have a capable 3d printer.

**Comment by andulv** [comment]
@64bandil Do you know anything about releasing STL or other files for 3D printing? I have not looked into that, except from confirming that I could open the .STEP and it seemed to be good.

**Comment by dkuchay** [comment]
May I request access to this step file? I see a src folder and within that two more folders. Commands and common. I do not see a step file in the code. Only .py and .md files within.

**Comment by 64bandil** [comment]
> @64bandil Do you know anything about releasing STL or other files for 3D printing? I have not looked into that, except from confirming that I could open the .STEP and it seemed to be good.

We have both STL and STEP files available. I usually prefer STEP files myself, because it allows you to make simple modifications to the parts, whereas STL files are more locked. Are the STEP files in this repository?

**Comment by andulv** [comment]
I have now uploaded the .STEP file, it is the same file I received via Google Drive when I received the code.

**Comment by dkuchay** [comment]
Thank you! I can print a replacement part for my machine with this. Appreciated. Is there license attributed with this file? I run a 3d printing parts store on Etsy.com and wondered about listing parts printed from this file for sale there? This is for others in the community to be able to obtain 3d parts for their Merlin units as needed. Thank you again.

**Comment by Mtoh2004** [comment]
A parts source would be awesome.  Let us know if and when you can build parts and pieces.

**Comment by dkuchay** [comment]
My pleasure. The irony of my machine needing an arm is the catalyst here. By the step file it appears to be that the material used is mentioned. ASA. Is there reference to a manufacturer used that anyone has within eyesight? I want to make as authentically as possible. My store is https://3dtpu.etsy.com. If that does not work internationally I can look into other options. I will have Arms photographed and listed as soon as I get the correct filament in hands. If there are other parts that I should be focusing on please do suggest.Thank you!Daryl On Apr 9, 2024, at 3:22 PM, Mtoh2004 ***@***.***> wrote:﻿
A parts source would be awesome.  Let us know if and when you can build parts and pieces.

**Comment by andulv** [comment]
@dkuchay License is GPL v3. 
From my understanding that means that you are allowed to do anything with those files, including printing and selling. 

But any changes (or derivative work) is also GPLv3 and you have to publish/share the changes if you distribute the result. 
So if you split them .STEP file, convert it to other format or do any other changes before printing and distributing, you also have to publish/distribute the changes with a GPL v3 license. 

https://fossa.com/blog/open-source-software-licenses-101-gpl-v3/

**Comment by dkuchay** [comment]
Thank you, @Anders!

Since I am not a designer I don’t foresee any modifications or changes however I do see the original license in the repo and will include it in the unforeseeabke event that I do. 

Just ordered poly maker ASA filament due to arrive tomorrow. I use a Bambu Labs X1C printer and poly maker filaments work well with it. Hoping to have replacement arms listed for tomorrow night or Wednesday by mid day. Barr any settings fiddling or bad testing results. 

Out of curiosity, was the glass dish custom made? 


Many thanks to all!

**Comment by dkuchay** [comment]
I have the first part listed however I had a change of heart on including these items within my hobby store that sells remote control quad copter parts. I started a second Etsy store that is international and the listing is here:

 https://www.etsy.com/listing/1712105629/merlin400-elevator-arm-right

As filament arrives I will make / photo the left arm and list it as well. Revise the first with photos of actual printed part. Etc. The store interface has a button for requesting a custom order for anything that I am not listing. The original plastic almost looks like it is impregnated with a metal..? 

If any issues are visible with how I have created and or listed the above link please advise so that I can fix.

**Comment by Mtoh2004** [comment]
Can you give me your advice regarding the asa vs asa-cf options?

Are the ones that came with Merlin ASA?

Thanks!

**Comment by dkuchay** [comment]
@Mtoh2004 - Still awaiting the answer for your second question. I plan on testing the cf-asa to see if there are any longevity differences. That material will be available tonight and I will photo upon completion of each arm / update. Would probably be good to ask on the other platform if aiming at me / shop. If aiming at owners of this repo I shut my mouth. On Apr 11, 2024, at 10:46 AM, Mtoh2004 ***@***.***> wrote:﻿
Can you give me your advice regarding the asa vs asa-cf options?



Are the ones that came with Merlin ASA?



Thanks!

**Comment by 64bandil** [comment]
> My pleasure. The irony of my machine needing an arm is the catalyst here. By the step file it appears to be that the material used is mentioned. ASA. Is there reference to a manufacturer used that anyone has within eyesight? I want to make as authentically as possible. My store is https://3dtpu.etsy.com. If that does not work internationally I can look into other options. I will have Arms photographed and listed as soon as I get the correct filament in hands. If there are other parts that I should be focusing on please do suggest.Thank you!Daryl On Apr 9, 2024, at 3:22 PM, Mtoh2004 ***@***.***> wrote:﻿ A parts source would be awesome. Let us know if and when you can build parts and pieces. —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

All parts are made in prusament PETG. We use galaxy black and white PETG. Alot of the parts are printed using heavily modified gcode to increase strength and gas tightness etc. Give it a whirl with prusament PETG. 

The big white main block (the manifold) is hard to print and is modified in so many places it gets you dizzy.

Ill do my best to support your printing efforts :)

Cheers!
Peter

**Comment by dkuchay** [comment]
Thank you Peter! 

I will order the rolls and report back if I run into a well on print settings. 


Appreciated, thank you!

Daryl
