### ISSUE TITLE
System software with local app (remove dependency on external server)

### ISSUE THREAD

**Issue by andulv** [64bandil/merlin400#3]
Changes to the existing Merlin400 system application ("drizzle"):
- [x] Add HTTP API for all operations performed by the app (or other external input)
- [x] Remove existing socket (666) code
- [x] Remove existing code for AWS connectivity
- [x] Serve files needed for the app (html, js, css) from the Merlin400 system application

Changes to the app:
- [x] Replace communication to AWS with communication to Merlin400 HTTP API

**Comment by andulv** [comment]
I have completed first working version where all communication is replaced by HTTP API.
It seems to be working, but I have only done superfluous testing so there are guaranteed bugs and issues.

@64bandil Please take a look at the code and see if you agree with the changes I have done. Let me know if you see anything that seems wrong or suspect. :)

**Comment by andulv** [comment]
Instead of porting the old React app I ended up rewriting it in pure html/js/css.
The current version in main seems to be stable and is ready for preview / testing.

**Comment by chandz102** [comment]
Hi Anders, I installed and tried it out, webpage looks good, but when I ran the heating program to warm oil, it made some funny noise and the LED light on the heating arm was flicker and turning on and off

**Comment by chandz102** [comment]
Hi again, Also tried with distill only, same issue made some really funny noise and the led light on the heating pad was just flickering randomly - did not look safe and sounded worse, so stop program and went back to original firmware

**Comment by andulv** [comment]
@chandz102 I believe this might be due to the old application still running. There was a typo in the instructions (readme file) for stopping the old application. It said "Drizzle" while it should be "drizzle" (all lowercase),

I have now updated the instructions for installing and starting the application.  In addition to fixing the typo the instructions now documents how to start the application as systemd service instead of starting it directly in terminal.

I followed these instructions myself on a "clean" machine and everything semmed to work.

**Comment by chandz102** [comment]
Sweet! I’ll give it another try when I get home

**Comment by chandz102** [comment]
@andulv that did the trick, runs perfect now. Just started a program 1 and all seems great. Good work!

**Comment by chandz102** [comment]
Are you also working on the maintenance and Settings tab? Just curious , as I really like the local app, I have already set up some port forwarding so I can access the machine from out and about :)

**Comment by andulv** [comment]
@chandz102 Yes. I have created issues #6 and #7 to describe the plans for those two tabs.

**Comment by chandz102** [comment]
@andulv so cool mate! Amazing!!

**Comment by andulv** [comment]
Closing this issue now as the app is now ready for testing and remaining work will be tracked in new issues.
