### ISSUE TITLE
Vacuum required for extraction needs to be lowered from 225 mbar to 300 mbar, to lower failure rates on the new pump generation

### ISSUE THREAD

**Issue by 64bandil** [64bandil/merlin400#4]
**Describe the bug**
Too many errors during initial error check 

**to fix**
Please change: 
"maximum_vacuum_pressure": "225", (line 524 in module_HardwareControlSystem.py) 
to 
"maximum_vacuum_pressure": "300", (line 524 in module_HardwareControlSystem.py) 

and push. 

I allready changed it in gitlab, where we have our CI/CD system and pushed to the amazon repos, but the changes needs to be reflected in the open source version. Can you guys handle this? Im not proficient in GitHub.

**Comment by andulv** [comment]
Fixed. :)
